### ISSUE TITLE
Membership request form

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#20] opened 2016-06-14 11:34 UTC
Details to come...

**Comment by fosterlynn** [comment] 2016-06-14 12:14
Here is some information from a Freedom Coop assembly: 

so, this means form -> acceptation -> OCP limited member -> faircoin payment -> OCP full member (with a pending role until they payment is confirmed). This part we should ask lynn and bob, if there are any concern (This role also could be useful when someone is member but has acumulated pending fees). This fee can be supplied by hours of work: form -> acceptation -> OCP limited member -> 6 hours of work -> OCP full member.

**Comment by skoria** [comment] 2016-08-06 10:26
this task may be a duplicate of #86 which is more elaborated now..

**Closed** 2016-08-09 19:38 UTC
Labels: enhancement
