### ISSUE TITLE
Upgrading django from 1.4 to 1.6

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#22] opened 2016-06-15 15:53 UTC
From django 1.4 to 1.5
================
[This site](https://nicksergeant.com/upgrading-from-django-1-4-to-django-1-5/) helped a lot.
- Changed *django 1.5* in requeriments.txt
- First errors in tests: *direct_to_template* -> Solved looking for ocurrences with *grep -r 'direct_to_template' ./*
- Second errors in tests: *path to a view function as a string* Solved as described [here](http://stackoverflow.com/questions/14882491/django-release-1-5-url-requires-a-non-empty-first-argument-the-syntax-change#15373978). This method for changing templates gets some errors in some files, a double quotation marks. It can be searched with:
```
grep -r "url \"'" ./
```
- Name of template in valueaccounting/urls.py
- Error in line 189 in valuenetwork/valueaccounting/tests/test_explosions.py corrected by @bhaugen 
- USE_TZ in settings.py
- Changed and tested with *django 1.5.12* in requeriments.txt

- fixed some addition unstringified urlnames where the sloppy programmer who shall remain unnamed did not leave a space between {% and url, so @XaviP 's grep didn't find them.
- fixed more "'urlname'" instances in files that had url_from_future so they were all ready stringified.
- this is about changing to https, not 1.4 to 1.5: tile.osm.org gave insecure responses to https requests, so I replaced them with mapbox tiles.
- removed a link to an obsolete page

From django 1.5 to 1.6
================
- Changed *django 1.6* in requeriments.txt
- No more simplejson: *DeprecationWarning: django.utils.simplejson is deprecated; use json instead.*
```
grep -r 'from django.utils import simplejson' ./
grep -rl 'from django.utils import simplejson' ./ | xargs sed -i s@'from django.utils import simplejson'@'import json as simplejson'@g
```
*json* needs a local name (*simplejson*) since in code there's a variable called *json* that conflicts.
- Django 1.6 changed the default value of BooleanField from False to None. It seems that doesn't make problems since we create a new db.
- django.conf.urls.default doesn't exist no more, but ocp seems already adapted to this deprecated.
- Add in settings.py:
```
TEST_RUNNER = 'django.test.simple.DjangoTestSuiteRunner'
```
This is for django 1.6 to use old kind of tests, but django 1.8 will need the new ones. See:
https://docs.djangoproject.com/es/1.9/releases/1.6/#new-test-runner
- Seems that settings.py file now expected ALLOWED_HOSTS and SECRET_KEY when deploying.
- Changed and tested with django 1.6.11 in requeriments.txt

**Comment by bhaugen** [comment] 2016-06-15 16:14
When you are ready, you can do a pull request to https://github.com/FreedomCoop/valuenetwork/tree/django16

**Comment by bhaugen** [comment] 2016-06-15 21:43
Finding bugs in 1.5 when I run it from the browser. Will need to do the same for 1.6.

@XaviP Let's slow down a minute before going to 1.7 to figure out how to handle the bug fixes for 1.5.

**Comment by bhaugen** [comment] 2016-06-15 22:43
This is partly because we don't have browser regression tests. We probly should, but who's got the time?

**Comment by XaviP** [comment] 2016-06-16 05:05
> Let's slow down a minute before going to 1.7 to figure out how to handle the bug fixes for 1.5.

Yes, I stop here. After the pilot, we will see.

**Comment by bhaugen** [comment] 2016-06-16 11:26
Here's my first set of bug fixes for the django15 branch:
https://github.com/FreedomCoop/valuenetwork/commit/d23c14eee95f56d39744c0cc4611d5112b391d75

I'll probably have more, doing more browser smoke-testing this morning. Then we need to get those into the django16 branch, right? Or what? @fosterlynn got any ideas about how to handle this? (She has more git branching experience than I do...)

**Comment by fosterlynn** [comment] 2016-06-16 11:44
Yes seems like we need to finish testing 15, then get the fixes from 15 branch into the 16 branch, just merge it in, then start testing the 16 branch.

**Comment by bhaugen** [comment] 2016-06-16 19:09
Summary of additional changes
From Django 1.4 to 1.5
==================

* fixed some addition unstringified urlnames where the sloppy programmer who shall remain unnamed did not leave a space between {% and url, so @XaviP 's grep didn't find them.
* fixed more "'urlname'" instances in files that had url_from_future so they were all ready stringified.
* this is about changing to https, not 1.4 to 1.5: tile.osm.org gave insecure responses to https requests, so I replaced them with mapbox tiles.
* removed a link to an obsolete page

**Comment by fosterlynn** [comment] 2016-06-16 19:14
I merged branch django15 into django16, so now we can work on django16.

**Comment by bhaugen** [comment] 2016-06-16 20:46
Got django16 up and running, and it's a lot cleaner than django15, at least at first glances.

**Comment by XaviP** [comment] 2016-06-16 21:03
ueeeeeeeeeeeeeeeeep!

**Comment by bhaugen** [comment] 2016-06-16 22:01
So we're making progress. 1.7, unfortunately, is the oldest supported version.

**Comment by XaviP** [comment] 2016-06-17 10:47
mmh... It seems that we can still use the old test framework in 1.7 (but not in 1.8)

**Closed** 2016-07-08 14:18 UTC
