### ISSUE TITLE
What next for invoice numbers in OCP?

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#181] opened 2016-11-07 15:02 UTC
Now: https://testocp.freedomcoop.eu/work/invoice-number/

* Needs more testing. 
* A page showing all invoice numbers, including who created them, has been requested.
* What else?
* What are the priorities?

**Comment by mario567** [comment] 2016-11-07 16:43
- Having an invoice blueprint (excel) to download for the members on the same page of the invoice number creation. (priority)
- This whole page should go under the menu point "membership options" called "Invoicing service"
- Perhaps the option and space to upload the prepared invoices by the members

**Comment by bhaugen** [comment] 2016-11-07 19:21
> Having an invoice blueprint (excel) to download for the members on the same page of the invoice number creation. (priority)

Does such a blueprint exist? I'm also curious if excel is actually a requirement, or if something non-proprietary would do (like a plain csv).

**Comment by mario567** [comment] 2016-11-08 12:26
yes we have one. Think i send it to you already via telegram when we talked about that but i can do it again if you cannot find it. Another format can work as well anyway. Its just necessary that members can fill in certain fields by themselves, like name, adress and VAT of the client, date, invoice number etc.

**Comment by bhaugen** [comment] 2016-11-08 12:48
Oops, sorry, I forgot. I have it from when you sent it in telegram. I'll add it to the invoice-number page.

**Comment by mario567** [comment] 2016-11-10 12:09
okay Bob thanks, did you add it already there? cannot see it yet

**Comment by bhaugen** [comment] 2016-11-10 12:26
No, haven't had time yet. Will do tomorrow latest, and get back to work on OCP more generally.

**Comment by bhaugen** [comment] 2017-01-26 20:12
Historical note: I added the blueprint to the invoice number page, but was told it could not go into the github repository, so I removed it again. And this issue has waited for more than two months for more definition and instructions.

**Comment by enricduran** [comment] 2017-01-26 22:04
Im not sure which kind of requirements are pendingm but will try. A pending point is if there is a need of blueprint to have inside OCP but we can not publish it on github, there is a way to do that?

Otherwise, there was a proposal of more than a blueprint, to provide a closed pdf with the invoice done after filling a form. This is pausible at dev level?

**Comment by bhaugen** [comment] 2017-01-26 22:07
>  if there is a need of blueprint to have inside OCP but we can not publish it on github, there is a way to do that?

I think so. Will try an experiment on testocp.

>  there was a proposal of more than a blueprint, to provide a closed pdf with the invoice done after filling a form. This is pausible at dev level?

Do you mean, provide a form to fill out to create an invoice, and generate a pdf from that, where the pdf is only accessible by the person who filled out the form?

**Comment by enricduran** [comment] 2017-01-26 22:21
> 
Yes I mean just what you said. Generate a pdf that is accesed by the person, together with the admins. And then he/she can download for sending to the client

**Comment by bhaugen** [comment] 2017-01-26 22:28
> Generate a pdf that is accesed by the person, together with the admins. And then he/she can download for sending to the client

I think so, but I think it would be a lot more work than putting a blueprint file on the server but not in github. So I'll try that first, if that is ok.

**Comment by enricduran** [comment] 2017-01-26 22:30
I can confirm that tomorrow after discussing with other people sensible about it

**Comment by bhaugen** [comment] 2017-01-26 22:32
I'll repeat my edit in the comment above, because the edits don't cause another notification: maybe we should ask @bum2 what he thinks about that, because he was the one who objected to the earlier blueprint file, and Mario thought it might have been more than just that it was on github. He might have objected to something about the whole idea of a blueprint file.

**Comment by bum2** [comment] 2017-01-26 23:47
We have already the invoice numbering in prod, that's enough now, but i'm not sure if Mario has been using them or not. To have a blueprint in the repo makes no sense for basic security reasons (everybody can make an invoice and send to someone else with our real data!)... the only way i see is the pdf generation with invoice data gathered in a form, as you said. That means we are really doing the gestioCI job directly in ocp, and that is not a bad idea. With just a bit more work we can have the automatic fees calculations or whatever accounting screen is needed in near future, perhaps faster than integrating with gestioCI (because they still have many issues)... let's see.
I will like a lot if you can think about the 'FairCoin' resource type, if it makes sense or not to connect exchanges made with such a resource type with the wallet, or have the wallet history also as exchanges history (made with that 'resource type'), or link to the wallet when doing a fair transfer in the exchange-logging page, or having the faircoin balance as a resources to pick from or adding new fairs when doing a transfer, or....
Also to say that the db strings issue is still pending (is very simple!) and will be needed for the pdf generation (and many other places)... Keep in mind that the real legal data needed in an invoice should never be on repo files nor code.

**Comment by bhaugen** [comment] 2017-01-27 11:27
> invoice data gathered in a form...With just a bit more work we can have the automatic fees calculations

That would be a big advantage of that approach. Wouldn't be difficult. Would require a new model and modelform, which is not a big deal, but somebody (other than me) would need to figure out which fields should be on the form.

Also, which app should it go into? I assume the work app.

Re the faircoin questions: I am still very slowly making progress on this issue: https://github.com/FreedomCoop/valuenetwork/issues/203

Sorry to be slow, but I got a lot to learn about faircoin processing. I think I'd want to have solved that one before connecting the wallet addresses to exchanges. Also, the exchanges seem to be mostly membership fees, I don't see anything that looks like it was from exchange-logging.

> Keep in mind that the real legal data needed in an invoice should never be on repo files nor code.

Doesn't it need to be on the invoice? If so, how does it get there? Have the code take if from a file on the server, that is not in the repo?

**Comment by bhaugen** [comment] 2017-01-27 11:29
P.S. the difficult part of form-to-pdf for me is generating the pdf, which I have never done before. But I know it is doable:
https://docs.djangoproject.com/en/1.8/howto/outputting-pdf/

**Comment by bum2** [comment] 2017-01-30 23:29
I've done many times automatic pdf's on the fly, but never in phyton... Must not be much hard. The information can not come from any file, not in repo, not in server. It just needs some data from the database. For this and many other things is needed from day one a system to store and retrieve strings from the db, the old issue still open... something like the help system will suffice (but hopefully translatable, the other big old pending issue).

Once the pdf is produced, then yes it becames a file we have to save somewhere (not only the user downloading the pdf) in a very secure folder. 

The main point i want you to understand is that a blueprint is something that can be edited at wish and we need exactly the opposite. A non editable pdf is just a small minimum of safety for the project. I've seen many big mistakes done by members without enough knowledge, or care, or time, or even lack of good will sometimes.

**Comment by bhaugen** [comment] 2017-01-30 23:39
We got two issues here:

1. The design of the model and form for the freedom coop member to enter for the invoice. What is the structure? What are the fields? I think all that information would saved in the database, but you could explain what should not be saved of the info the member enters.
2. The information that is sensitive and must be kept secure, and how we handle it to keep it secure. I am assuming now that the sensitive information is a small part of the info on the invoice, and not the info that the member enters, but again, you could explain what is wrong with that assumption, and why.

I'd like to have some whys in this conversation, because otherwise I am flying blind, just reacting to complaints. If I understand what is sensitive and why it is sensitive, I can deal with it better.

**Comment by bum2** [comment] 2017-01-31 01:14
1- We'll try to figure-out the needed fields for the user in the next days... usually item lines for the invoice, customer data, etc. Yes all this will go in the db.
2- Sensitive information is not only users data but also our legal data. It can be only in the db also. I was proposing to put them on a table dedicated to such internal strings we need in some places. It can be similar to the help system, where using an 'identifier' string can retrieve a text from the db. Hopefully that model can be done by somebody (it's super easy). The real issue comes from the need to translate many db strings, not only these 'internal' ones but also the many db strings around (categories, types, names, descriptions, helps, etc)

**Comment by bhaugen** [comment] 2017-01-31 01:23
If I remember correctly, the legal data is maybe two strings, that could be in two fields, in some new model.

Do you think the db string translation needs to be part of this issue? Or not? If it is, it will be a long time before all this stuff is done. (This has happened before in OCP: loading a pile of somewhat-desired work onto an issue that could be limited a lot more and be done sooner.)

**Comment by bum2** [comment] 2017-01-31 01:39
Not needed the db translations for this release, but for the next one, so will be good to do the things with that in mind. We need a model for invoices, and that is a big one i can work on next release. But we also need a model for the internal strings, not only the few we need in the invoices but all the rest of strings pending to add in many places, explaining the tools, messages of emails, menu items, etc.

**Comment by capiscuas** [comment] 2017-11-20 10:57
As discussed in FreedomCoop and CommonManagement assemblies ...
FYI new developments are being done at 
invoices.freedomcoop.eu by santi using Odoo to create the invoice workflow that FreedomCoop needs.
In the future a ValueFlow layer can be added on top of Odoo to be compatible with OCP.

**Comment by fosterlynn** [comment] 2017-11-20 13:42
Closing per @capiscuas comment.

**Closed** 2017-11-20 14:28 UTC
Labels: discussion, enhancement, needs testing
