### ISSUE TITLE
Button "Contribute your shares"

### ISSUE THREAD

**Issue by bum2** [FreedomCoop/valuenetwork#106] opened 2016-08-12 14:49 UTC
The missing thing is to create a button like "contribute your shares" to click on it when is candidate and there are enough fairs in the account. Once clicked, disappears forever. This way we don't need to publish or say the 'membership-request' faircoin address, and we can keep the transactions only attached to members.
To place in the wallet page.

**Comment by bhaugen** [comment] 2016-08-12 16:48
I think this is a great idea, and will do it. I'll come back with some detailed questions after I think through all the implications and discuss with @fosterlynn

**Comment by bhaugen** [comment] 2016-08-12 22:20
Here's my first draft of a design for this button and the machinery behind it to make it work:

## Create a new Resource Type called something like Freedom Coop Share

Freedom Coop full members will be those who own at least one Freedom Coop Share. They can purchase more if they want.

## Create an Internal Exchange Type for purchasing Freedom Coop Shares. 

You call it anything you want. Exchange Types are configurable.

It will include a Transfer Type of Faircoins for Freedom Coop Shares.

## When a new member is set up:

* Create a Commitment using that Exchange Type for the new member to pay the 600 Faircoins for 1 Freedom Coop Share.

* Their Profile page could say something like:
    * Your Faircoin acccount balance is 800
    * You are now a candidate member of (whatever group we assign candidate members to, which I guess is the FreedomCoop Membership Request Group)
    * If you pay 600 Faircoins (or is it Fairs?) for 1 Freedom Coop Share, you will become a full member in Freedom Coop.
    * **The Button** (what should it say on it?)
         * When they click the button, it will send 600 Faircoins from their address to the Freedom Coop address,
         *  they will become the proud owner of 1 Freedom Coop share,
         * and they will be made a full member of Freedom Coop.

What do you think? Please comment and suggest improvements.

**Comment by bum2** [comment] 2016-08-12 23:06
Great! The number of shares depends on the membership form field, and the collective members are minimum 2 shares. They can set a bigger amount. The value of a share is really 30€ but now it means 600f internally. The name of the button can be "Contribute your shares".

**Comment by bhaugen** [comment] 2016-08-12 23:11
> "Contribute your shares"

Doesn't seem accurate to me. They are paying for shares. Whatever you want to call it, that is what is happening. In my draft design, they end up owning their shares. They are contributing 600 fairs per share.

I had not caught the change of 2 shares for collective members. Got it now.

**Comment by bum2** [comment] 2016-08-12 23:25
"Transfer your X shares" if you like more? (with the number of shares requested in the form) 
The button is only active when there are enough fairs in the wallet, and after sending the button disappears forever.
If you want to setup a resource called FreedomCoopShare, the value is 30 euros.
In a future version perhaps, the value of a share (30€) will get the official price from the getfaircoin.net/api/eur-fair (or /fair-eur or /ticker ) to translate in faircoin units, now is 600 fairs.

**Comment by bhaugen** [comment] 2016-08-12 23:32
I do want to set up a resource type called Freedom Coop Share. I don't think I want to get into currency value conversions unless we really need to do it. So do we want them to pay 30 euros or 600 fairs?

Anything more complicated than that is doable but I think up to the Freedom Coop gang to implement.

**Comment by bum2** [comment] 2016-08-13 17:17
Then put 600 faircoins, and if the price changes we can edit this field at later time if decided by the FC assembly. In any case it will be totally stable like now, because the assembly has decided so.

**Comment by bhaugen** [comment] 2016-08-13 17:22
Got it, will do.

**Comment by bhaugen** [comment] 2016-08-15 18:00
@bum2 -

> "Transfer your X shares"

I don't think that is any better than "Contribute". They are transferring Fairs from their Faircoin account to Freedom Coop's Faircoin account. And Freedom Coop is transferring 1 or 2 shares to them.

It's not so much which word to use, I don't care. It's about what is an accurate statement of what will happen if you click the button.

Here's what I got now:

![pay_for_shares](https://cloud.githubusercontent.com/assets/117439/17673702/f2d3e198-62e7-11e6-8ef5-5a4a1fa1c50d.png)

You may not like the words, but is the statement accurate? If so, please improve the words. If not, please correct the meaning. (The explanation says 1200 fairs and 2 shares if the agent is a collective.)

**Comment by bhaugen** [comment] 2016-08-16 00:51
Here's what I got now if you don't have enough Fairs in your account:
![not_enuf](https://cloud.githubusercontent.com/assets/117439/17684428/2c255f88-6321-11e6-8bab-f96b76f1e242.png)

You, of course, can change the wording, styling, or whatever.

I got closer to making the button work today, but did not get finished.  Here's what I understand about the rules:

* When new membership requests are processed, the new member gets put into the Membership Request group as a candidate.
* When they paid 600 for an individual or 1200 for a collective membership, they get 1 or 2 Membership Shares, and they are put into Freedom Coop as a full member.

Right?

**Comment by bhaugen** [comment] 2016-08-16 11:45
@bum2 - another question. I understood from Telegram and other conversations that new candidate members were supposed to pay for their shares from an OCP faircoin address to the Freedom Coop faircoin address. That is the way I am implementing the button. Is this correct?

If so, the candidate will need to put some fairs into their OCP account. If we hide their faircoin address, as E says we should do, how can they get any fairs into the OCP account?

(P.S. I have not hidden their address yet. And if the goal is to prevent them transferring fairs from their OCP address to external addresses, we can do that in other ways.)

**Comment by bhaugen** [comment] 2016-08-16 14:11
And yet another question: if I understand correctly, new members are associated with the the Membership Request group as a candidate.

When they pay for their shares, they will be associated with Freedom Coop as an active (full) member.

But what should happen to their previous association with the the Membership Request group? Should that be deleted, or promoted from candidate to active?

If no response, I'll just promote that to active membership, too.

**Comment by bhaugen** [comment] 2016-08-16 16:07
Also @fosterlynn - I'm working with Membership Contribution Exchange Type you created, and wonder if it should have its own special use case? As it is now, the use case is Internal Exchange, which you think is confusing people anyway, and most likely too broad.

**Comment by bhaugen** [comment] 2016-08-16 16:09
P.S. @fosterlynn - another question. (I could just ask her, she sits right next to me, but she is in the midst of conducting a training session for Freedom Coop admins and I don't want to interrupt, but then again, I don't want to forget these questions.)

Do Transfer Types have any configured relationship to Event Types? If so, I can't find it...If not, should they?

**Comment by bhaugen** [comment] 2016-08-16 19:55
I think I have this button working locally. Here's how it works now:
* If the user-agent is a candidate member, their profile page shows a box explaining how to pay for a membership share.
* If they have enough faircoins in their account, they get a button to pay for their 1 or 2 membership shares.
* When they click the button, 600 fairs per share will go to Freedom Coop's faircoin account, and the membership share(s) will go to the user-agent.
* The user-agent will be promoted from candidate to active membership in the Membership Request Group, and also made an active member in Freedom Coop.
* The box and button will go away, never to return again.

Does that seem correct?

**Comment by fosterlynn** [comment] 2016-08-16 20:05
>Also @fosterlynn - I'm working with Membership Contribution Exchange Type you created, and wonder if it should have its own special use case? As it is now, the use case is Internal Exchange, which you think is confusing people anyway, and most likely too broad.

Actually I was thinking that we need to consolidate to one use case, just Exchange.  The incoming, internal, and outgoing is confusing.  I can't think of anything we need it for except Demand vs Supply vs Organization pages to access the reports or create exchange, so if we structure the nav differently, maybe that distinction could go away.  (But not until then.)

**Comment by fosterlynn** [comment] 2016-08-16 20:06
>Do Transfer Types have any configured relationship to Event Types? If so, I can't find it...

No.  A transfer always has a Give and/or a Receive type event.

>If not, should they?

I can't think of a reason to have that.

**Comment by bhaugen** [comment] 2016-08-16 23:20
I pushed this to the [membership_share branch](https://github.com/FreedomCoop/valuenetwork/tree/membership_share).

@XaviP can we deploy this branch on testocp?

The share price depends on the price per  unit of the [Membership Share resource type](https://testocp.freedomcoop.eu/accounting/resource-type/8/), so by setting the price very low, we could test without sending too many fairs floating around the network.

I'll get Lynn to help write up a more complete test plan when we are ready to test. This is really raw code and I expect bugs. I can't test all the faircoin transactions locally without a lot more set up than it will take to do it in testocp, and then more people can help to break it.

**Comment by XaviP** [comment] 2016-08-17 05:52
@bhaugen deployed membership_share branch in testocp

**Comment by bhaugen** [comment] 2016-08-17 05:52
Ok, great!

**Comment by bhaugen** [comment] 2016-08-17 06:07
Here's more of a test plan:
* Since testing this requires sending FairCoins from your address to the Freedom Coop address, I think it would probably be easier to set the price of a [Membership Share resource type](https://testocp.freedomcoop.eu/accounting/resource-type/8/) pretty low.
* Then create new Agents with users and associate them with the Membership Request Group with the association status "candidate". (This is what some of you have been doing to create new agents and users.)
    * Create at least three individuals and one collective.
* The new agents should have FairCoin addresses. Send them some Fairs.
    * Have one with enough Fairs to cover the share price, one with not enough Fairs, and one just enough Fairs.
* Log in as each agent and go to their work profile.
* You should see a box on the upper right giving the instructions for what do do.
    * The agents with enough Fairs should see a button to pay for their shares. Click the button. They should become active members of Freedom Coop and the "candidate" flag on their association with the Membership request group should go away.
    * One their Agent page in the coop admin app, they should also own 1 or 2 Membership Shares in their Resources. (You might need to scroll down to see those.)
    * And you should see the FairCoin transactions on the event histories both for the agent and Freedom Coop.

Please add any problems you run into here as comments.

**Comment by bhaugen** [comment] 2016-08-17 06:12
Also, don't worry about the wording of the box on the profile page. But do suggest improvements.

**Comment by XaviP** [comment] 2016-08-17 14:10
Tested button:
- First I have not enough funds to pay, and the message indicates correctly how to proceed.
- When transafered some FAIR, the button apears, with clear message of what is going to be done.
- When button pressed, error:
```
AttributeError at /work/share-payment/20/

'NoneType' object has no attribute 'state'

Request Method: 	POST
Request URL: 	https://testocp.freedomcoop.eu/work/share-payment/20/
Django Version: 	1.8.13
Exception Type: 	AttributeError
Exception Value: 	

'NoneType' object has no attribute 'state'

Exception Location: 	/home/ocp/app/valuenetwork/work/views.py in share_payment, line 298
Python Executable: 	/usr/bin/python
Python Version: 	2.7.9
Python Path: 	

['/home/ocp/app/valuenetwork',
 '/home/ocp/app/env/lib/python2.7/site-packages',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/home/ocp/app/valuenetwork/']

Server time: 	Mié, 17 Ago 2016 14:07:04 +0000
```

**Comment by XaviP** [comment] 2016-08-17 14:13
Sorry, the test was with my admin user, maybe it's not a good test.

**Comment by bhaugen** [comment] 2016-08-17 15:24
The code is looking for an association in the "candidate" state so it can promote you to "active".

I'll make it more forgiving. I have a few places to do that, will do this one first.

**Comment by bhaugen** [comment] 2016-08-17 15:38
Made this less fussy in latest commit to the membership_share branch.

**Comment by bhaugen** [comment] 2016-08-17 15:38
Okay to close?

**Comment by Holofractographic** [comment] 2016-08-17 15:47
I see that the button send the faircoin to the freedom coop address and not to the membership address is the same address???

**Comment by XaviP** [comment] 2016-08-17 16:01
Yes, confirmed, faircoin goes to Freedomcoop address.

**Comment by bhaugen** [comment] 2016-08-17 16:16
So it is now going to the right place? If so, good! Got at least one thing right.

**Comment by XaviP** [comment] 2016-08-17 16:22
Yes, only the address, the rest of process with button was right with a candidate.
@bhaugen thank you very much!

**Comment by bhaugen** [comment] 2016-08-17 16:26
I still don't understand if I should change the address the button sends the faircoins to, or leave it the same.

**Comment by bhaugen** [comment] 2016-08-17 16:50
@bum2 @XaviP should I change the address the button send fairs to? I have time right now to do it.

**Comment by bhaugen** [comment] 2016-08-17 18:36
I am now waiting for 2 decisions:
* where (what group's faircoin address) should the payment go to?
* should the button buy the required number of shares (1 or 2, or  the number they put in their membership request?

I already made some guesses to get a button out on testocp to test. Now I would like some consensus decisions please.

**Comment by bhaugen** [comment] 2016-08-17 19:48
If I am picking up the chatter correctly, I should send the payments to the Membership Request group.

I'll use a setting for payments:
#ID of group to send payment to
SEND_MEMBERSHIP_PAYMENT_TO = "FC MembershipRequest"

Only problem is the ID is different between textocp and prod ocp.
That's prod ocp above. Testocp below:
"FC_MembershipRequests"

So could somebody please make them the prod ocp ID the same as the testocp one? Because that is what I will put in the settings for testing.

**Comment by bhaugen** [comment] 2016-08-17 20:09
The consensus on number of shares is that the button should pay for the number they offered to buy in their membership request.

**Comment by bhaugen** [comment] 2016-08-17 20:56
I implemented both of those decisions (number of shares and pay to Membership Request group). Committed and pushed.
Ready to be deployed to testocp and retested, because that was a more complex set of changes than it might have seemed.
I did test it in my development environment, but you know how that goes. Need more testers and more ways to break it.

For number of shares, I used which ever was greater between the required number and the number they put in their membership request. I think the request form minimum was 1 share, but the rule I was told for collectives is that the required number for membership is 2.  Let me know if any of that is incorrect.

**Comment by bum2** [comment] 2016-08-19 00:06
The button feature works good, tested on testocp. Thanks a lot Bob!
I still think the best page for it is the Wallet page (better than the profile page), after the table but before the paying form, and even i think it can be good to deactivate the paying form (to transfer out) and activate it when membership shares are payed with the button (only for 'candidates', not for the future 'participant' users, because they will be able to transfer out from the begining). I don't mean to hide the form, just show with inputs deactivated.
Another thing it can be improved is the button text, how about 'Pay your membership shares' ?
By the way, let's comment here some improvements to the Wallet page: The Change button has no sense in the work app (to change only the name of the wallet perhaps, but not 'price per unit', 'location' and all that stuff), i think it can be removed. Also the last table field, 'record created by', can be removed in the work app (not useful and normally 'None').

**Comment by bhaugen** [comment] 2016-08-19 00:13
Some replies to @bum2 's comment:
* Feel free to improve the text, both on the button and the box around it.
* What is the wallet page? Where is the wallet page? What Change button? I am bewildered.
* Technically (which may not matter), the OCP members do not have their own wallet, they only have addresses (which we are currently calling Accounts in the work app) in the single wallet within OCP.

**Comment by bum2** [comment] 2016-08-19 00:28
I know its not a real complete wallet, but is their faircoin online account in ocp (perhaps i change the name to 'Faircoin account' in the workapp menus).
The page i'm refering is the Faircoin Account page using the work/templates/work/faircoin_account.html template, now called just 'Wallet' in the candidates and members menus.
The Change button i say is in this page, opening a form to change the 'faircoin address resource' data. We can remove the button and the form, and the table row i said.

**Comment by bhaugen** [comment] 2016-08-19 01:01
This page? /work/manage-faircoin-account/45/
Yeah, the Change button can go away.  And whatever else you want.

I've been calling it Faircoin Account in the work app, but I don't really care.

**Comment by bhaugen** [comment] 2016-08-19 01:05
Problem with putting the Pay for your membership shares button there is that it is obscure. I think it should be on the landing page, first thing they see, not the last thing that they need to look for. 

The landing page now is their dashboard, which has been renamed in your new menus, but that's still what the url says. I proposed recently to change their landing page to their profile, which is where the button lives now. It could go anywhere pretty easily, but I think should go on the first page they see.

**Comment by bum2** [comment] 2016-08-19 02:11
I think different: is long ago i'm trying to define a landing page for candidates and a landing page for members, with just the basic descriptions and links to the available tools (dashboard). The page for the 'pay shares button' is the wallet page, because is where you go to move coins. Nothing obscure (also now the 'wallet' page shows in candidate's menu), just the right place for sending coins and use your online account. 
In a landing page we will explain and link to this payments page ('wallet'), but for me is confusing in the profile page, and also i don't like the idea of making the profile as the landing page. Actually the landing is the page where you see the initial membership tasks, and you can read and follow them, so its not so bad but anyway a landing page on its own i think is the best option, specially for members.
The candidate's landing-dashboard page can be very more simple than the member's one. It can be the next one i do, but only if the created tasks instructions are not enough to guide the 'candidate' to his online account or 'wallet' page, so he can fill-in the account and then pay the shares with your button (in that page).

**Comment by bhaugen** [comment] 2016-08-19 12:32
If you don't show the simple payment method in the first place a new candidate lands after logging in, then you need either that task that the coop admins are creating now, or some very clear instructions on the page where they land.

With the button and instructions on the landing page, you don't need the task at all.

The reason I put it on the profile page is that the candidates associations are shown there, and when they click the button to pay, their associations are immediately updated and they can see also see that they now own a membership share. So the effects of the button are shown immediately.

That would not be true if you put the button on their faircoin account page. 

I don't actually care where it goes, I am just explaining why I put it where I did.  I did think about it.

**Comment by bhaugen** [comment] 2016-08-19 12:39
By the way, I think you could just move that whole div with the button in it to a different page and it would require only one code change, to return to a different page after it has done its fairly complex work.

Here's the method that does the work:
https://github.com/FreedomCoop/valuenetwork/blob/membership_share/work/views.py#L165

Here's the line of code that would need to be changed:
https://github.com/FreedomCoop/valuenetwork/blob/membership_share/work/views.py#L314

Just change the 'work/profile'.

**Comment by bum2** [comment] 2016-08-22 11:34
ok, the return page of the button form can be the new member's 'home' page...

Another related issue is this:
When the account is filled with enough fairs to pay the shares and instead of pushing the button you send out some fairs (the send form still active now), the button remains there until the sendout is in 'confirmed' status. In this case will be much better to calculate the balance using any status of the transactions,  a kind of 'fast-balance' to change the button state without waiting the confirmations of new block in the blockchain? i don't test, but i'm wondering what will happen if i press the button during that minutes, will the transaction happen even if i don't really have enough fairs? an error screen will come?
In another comment i was proposing to disable the send out form during the account fill-up and membership shares payment period, so this fail possibility don't exists, but the candidates cannot use the fair account to send-out, only members (and also the future 'participants').

**Comment by bhaugen** [comment] 2016-08-22 11:39
When the button was on the profile page, and you clicked it, the button went away. It it not wait until the transaction was confirmed.

I'm not sure what the logic should be (wait for confirmation or not), but something has changed in the overall logic when moving the button to a different page.

It's in master now, right? If so, I'll pull into my dev environment and see what's the diff.

**Comment by bhaugen** [comment] 2016-08-22 11:40
Re the balance: it's coming from the network, not OCP, so it should be pretty accurate, but possible race conditions can happen if something happens on the network to reduce their balance.

**Comment by bum2** [comment] 2016-08-22 11:43
yes the button block disapears if i click on it, but if i send out some fairs and there are not enough for the shares, the button remains there (only reacts by confirmed blocks, not ongoing operations or 'broadcast' status).
Another 'balance' function to make internal ocp fast calculation of it perhaps is needed.

**Comment by bhaugen** [comment] 2016-08-22 11:45
> yes the button block disapears if i click on it, but if i send out some fairs and there are not enough for the shares, the button remains there (only reacts by confirmed blocks, not ongoing operations or 'broadcast' status).

I don't get it, but will test it soon and report back here.

**Comment by bhaugen** [comment] 2016-08-22 12:19
I can't test again until I reconfigure the daemon for local use again. But I looked at the code:
https://github.com/FreedomCoop/valuenetwork/blob/master/work/views.py#L1101

There it is checking to see if the agent has a candidate membership. If not, it won't show the button. 

Then in 1109 it checks if the agent already has a membership share. If so, once again, it should not show the button.

Both of those changes are made when the button is clicked, without waiting for the transaction to be confirmed. 

In the template, it checks if payment_due. So I don't understand why the button is still appearing after it has been clicked. 

I'll be able to test it later. Right now, got a bunch of homestead stuff happening. Might take an hour or two.

**Comment by bhaugen** [comment] 2016-08-22 14:51
@bum2 I'm back, please ping me if I should do any more work on this.

**Comment by XaviP** [comment] 2016-08-24 08:03
The button is already in production. Can we close this issue?

**Comment by bhaugen** [comment] 2016-08-24 08:45
OK with me, but @bum2 - this was your idea. Is it closable?

**Comment by XaviP** [comment] 2016-08-24 10:34
Closing as it is already working in prod ocp. Please, reopen if needed.

**Closed by XaviP** 2016-08-24 10:34 UTC
