### ISSUE TITLE
Track external receivements of faircoins as events

### ISSUE THREAD

**Issue by bum2** [FreedomCoop/valuenetwork#203] opened 2016-12-27 23:10 UTC
In the account history page you should see all the transactions happened to this address. When filling-up the ocp fair address with external fairs it's needed also a event to track that, and the From field will not be an agent name but a external fairaddress. Now the balance is not correlated to the list of events because is missing the incoming external ones.

**Comment by bhaugen** [comment] 2017-01-03 18:42
If you look at https://ocp.freedomcoop.eu/accounting/resource/4/ and click Follow Chain, you will see
https://chain.fair-coin.org/address/fShUWoHSg3SxtN3ezVTWfoqdLPejYgMgzD

Seems like we should be able to pick up that info on the fly and show it on https://ocp.freedomcoop.eu/accounting/event-history/4/

If it exists. I'm seeing a lot of faircoin addresses in OCP that do not appear on the chain, for example:
https://ocp.freedomcoop.eu/accounting/resource/54/
https://chain.fair-coin.org/address/fVRdLE87ywagHTLkWf7B4y2f3DU1K59nFQ

Wonder why that is? I'll ask in telegram and see if anybody knows...

**Comment by bhaugen** [comment] 2017-01-03 18:51
I could see if I can do this one. @bum2 do you think this is the highest priority issue I could work on? Or do you think something else should come first?

And are you working on this one actively?

**Comment by bum2** [comment] 2017-01-04 02:10
I'm not in this issue, please do it if you can... will be good to have in ocp the same operations shown in the chain when seeing the address, so the total is clear and checkable.

**Comment by bhaugen** [comment] 2017-01-04 12:29
I took it, and will see what I can do.

**Comment by bhaugen** [comment] 2017-01-07 18:15
I'll start working on this tomorrow.

**Comment by bhaugen** [comment] 2017-01-08 19:55
@bum2 I'm working on this now, very slowly, to set up a test environment. One immediate question: do you know how to interpret faircoin transactions and address histories?  For example, how to interpret this?
https://chain.fair-coin.org/tx/edc2a43400b5e25331e5d8d12778563cd5c53d8fab99667443f5a25a2a4138ed#o1

Inputs
Index	Previous output	Amount	From address	ScriptSig
0	63526e40a8...:1	18.999	fPhpxGqcnWPkj9GFZrqmmmG1JEfikWe1r4	71:3044...0101 33:037e...3716
Outputs
Index	Redeemed at input	Amount	To address	ScriptPubKey
0	485a93f035...:0	1.099	fbuVYDupmaBm7hSSmh4So8tYUABxfQadf5	DUP HASH160 20:ef16...149b EQUALVERIFY CHECKSIG
1	ce5aa9196c...:0	17.899	fPhpxGqcnWPkj9GFZrqmmmG1JEfikWe1r4	DUP HASH160 20:6940...2fec EQUALVERIFY CHECKSIG

One of the outputs, Amount 17.899, goes back to the "From address" of the Input.

**Comment by bum2** [comment] 2017-01-08 23:32
I'm not sure but i think inputs in are made of chunks of coins of same age (like a bank-note of certain amount), and outputs send the intended coins to the intended address AND the 'change' back to the sender's address... I don't know if that behavior is due the actual POS algorithm and will change with POC or not.

But what i mean in the issue is more about what appears in the chain's address page (eg. https://chain.fair-coin.org/address/fbuVYDupmaBm7hSSmh4So8tYUABxfQadf5), all the operations of that address but in ocp...

**Comment by bhaugen** [comment] 2017-01-09 15:46
I'm starting to make progress on this issue, but it won't be fast. Lots of learning to do...will make regular progress reports here, one coming later today.

**Comment by bhaugen** [comment] 2017-01-09 16:26
Progress report: I finally made contact with the wallet in the shell again, so I can look at the transactions in more detail.
```
import electrum_fair
wallet_path = 'your/wallet/path'
storage = electrum_fair.WalletStorage(wallet_path)
wallet = electrum_fair.wallet.Wallet(storage)
address = 'a valid address in the local wallet'
history = wallet.get_address_history(address)
tx_hash = history[0][0]
tx = wallet.transactions.get(tx_hash)
```
But now I come to a show-stopper:
```
tx.input_value()
tx.serialize()
tx.inputs
#all give the same error message:
AttributeError: Transaction instance has no attribute 'inputs'
```

**Comment by bhaugen** [comment] 2017-01-12 12:32
Where I am at on this issue now:
* I got the transaction history of an address from electrum_fair_nrp as reported above.
* I am using an OCP database that I used for my initial tests of faircoin-ocp code, which corresponds to my local wallet.
* I have events in that OCP database that do not appear in the transaction history from electrum_fair_nrp, but they *do* appear in the chain, so they are valid events.

So I am wondering why these events, which were created from OCP via electrum_fair_nrp and represent valid, confirmed faircoin transactions, do not appear in the address history in my local wallet?

I also have a bunch of transactions in the address history from electrum_fair_nrp that do not appear in the OCP events, and am figuring out how to display them in the OCP faircoin account event history. But I don't know if I can trust them, either.

Will probably need to do some probing in the shell in testocp and maybe prod ocp to find out if that same anomaly (OCP events that show up in the chain as valid transactions but not in the local wallet) still happen there. I should be able to do that over the weekend.

**Comment by bhaugen** [comment] 2017-01-16 12:38
I'm trying to check out those event vs transaction anomalies in testocp, and ran into this problem:
```
ocp@vps245823:~/app/valuenetwork$ python manage.py shell_plus
ImportError: No module named pinax_theme_bootstrap_account
```
@bum2 - got any insight into that error? I don't know how the OCP software was installed in testocp.

**Comment by bhaugen** [comment] 2017-01-16 12:48
Trying to check out the same problem in prod ocp, ran into a different problem. I can get into shell_plus ok, but when I do, I am connected to a different database than the one used in production. I suspect it is the old sqlite db, while production is using PostgreSql. So something is configured wrong for using the shell there.

**Comment by bhaugen** [comment] 2017-01-19 15:09
Ok, got some results on the transaction anomalies in prod ocp. Can anybody explain what is happening here? Am I misunderstanding something? Or is there something wrong here? I had planned to use the address_history_info to supply the transactions that were missing from the OCP event history, but if I can't trust the address_history, I need to rethink.

I found 21 economic events representing faircoin transactions in the event history for the Faircoin address for FC MembershipRequest that do not appear in the address history as reported by electrum_fair_nrp.address_history_info(address). 

Here's that event history:
https://ocp.freedomcoop.eu/accounting/event-history/10/

Here are the first 10 of those transactions. Each of these are valid transactions, on the chain. 
* https://chain.fair-coin.org/tx/46d1a1ed4b2178d5f655076366115a5b763dcfd9c0feaa30fba47c9ff0026e38
* https://chain.fair-coin.org/tx/fef2c390f8caf5591df0d6393796ff685c7d54f9cf758630b305aaca6266c08c
* https://chain.fair-coin.org/tx/e4ee59ae8a9b1d851237efb80a66e601921a85cae9c8122a3a7feabe05ff757d
* https://chain.fair-coin.org/tx/2e968cba162660538db2d9b20a4038932c9223d0f0d878e509efb00b6ee71e0f
* https://chain.fair-coin.org/tx/aa6da7c80f0dca86a115063e162729524ab6636dd2fc160d1a9866286d02c3cf
* https://chain.fair-coin.org/tx/d86045f0d57bc378f584accff6a14796d8772ee6d9a73f33954e0bad422eabce
* https://chain.fair-coin.org/tx/3da6d771f3fe33d831b1c7ffbb8d8f83ef793381898153c9ecfffbb51e3c0f04
* https://chain.fair-coin.org/tx/1f7e6229dc47552304d387e4179fdd05884757e5cc3e1c07a7552d9892eec965
* https://chain.fair-coin.org/tx/2db38ef698bfa3e1c49c7dd484795fa1e0578b004233c53c83506b531290f572
* https://chain.fair-coin.org/tx/4c7c47e0df6a24a6907f1084ddf3ee3543f90a6e45f4c9d9276f3dd15ee5c29b

**Comment by bhaugen** [comment] 2017-01-22 18:35
Progress report: I got maybe halfway to a solution this morning. Got a little more work to do before I write up some tentative conclusions with some code, for a code review. Maybe mid-week, definitely by end of week.

**Comment by bhaugen** [comment] 2017-01-25 17:41
Ok, I am stumped again. Event history for the  in prod ocp contains 42 transactions:
https://ocp.freedomcoop.eu/accounting/event-history/10/

The chain has 43, so the event history is close:
https://chain.fair-coin.org/address/fEayVWxszDVJDEercVmWxPdi4YGTCxe84L

But electrum_fair_nrp.address_history_info(address) only gives me 20.

I have been hoping that the address history would give me the transactions that are out on the chain, but missing from the OCP event history (the transactions that were processed in OCP). But it doesn't. 

So how can I get all of the transactions that are out on the chain, to fill in the missing ones in the OCP event history? What am I missing? What do I not understand?

This is more evidence from shell_plus in prod ocp:
```
>>> fcr = EconomicResource.objects.get(id=10)
>>> fcr
<EconomicResource: Faircoin Address: Faircoin address for FC MembershipRequest>
>>> address = fcr.digital_currency_address
>>> address
u'fEayVWxszDVJDEercVmWxPdi4YGTCxe84L'
https://chain.fair-coin.org/address/fEayVWxszDVJDEercVmWxPdi4YGTCxe84L
>>> import faircoin_nrp.electrum_fair_nrp as efn
>>> info = efn.address_history_info(address)
>>> len(info)
20
>>> hashes = [i['tx_hash'] for i in info]
>>> len(hashes)
20
>>> hashes
[u'0956cc45b0683797a292844337d7dfe70db0e2f808e3dfebda911055f9027e99', u'2d758d178fc3b52e749b6a65e5e393dd4883a68ffe1b4cd2839a123168198c40', u'38a5e47067467749b86fab8708ea3b8e8ca47186d77cb7b0d70dd7ef6ff17934', u'cb77f6df4309d8c2129a159758b3863ede9077f251f750e2af0144424e709e31', u'b5c7b93a7166e11a0e20e674bd627f087afd8c0c72b8d840b2bb005740ec24d9', u'9117bbe7438bf253da3b79241a41799a73ada3c8dd2f5749c397c46c8f1c07cd', u'fff0ff08d657e1e90fc0f1ee73c68c314b1a56ed921ee735e3677201a63faac5', u'01ecfcd71bc1224f3a2edd73d4010b43200b68c57028a16a93c90f6c6aa3aa63', u'63f44a12d7f4159cf76c0c0af17f5e4371cd6a4e14f6f71d4949e3dae25880c4', u'f010fa8a20b2e828f75d69394d9bbf8a56a69546d53acf66ec652427c293538a', u'12434b150e8fd180ed0373635c05ba152ea048ae8d635b705c3c5f0148773e8e', u'58b5a4bb0561423b14a21e0af9d39cd90b40ca809c60465b614192887ac722d0', u'271ec3f5d556a64e79a9ecf9c1b6bff41e6c55c9d2ea4e3a43f0b5ad4bfb28a3', u'21c261659e06d2585dff7e747c98bb1d0783008b51ecbf72b6950687f275a898', u'42f6acd885b786f4bc7ccfd0283499b0e7f5f821777596a22c637eb9c17d457e', u'718d56cb921ddfda748235b22cea73d31ead9a687aa3ccb112d112385180d648', u'c54d351e741c7f0a4fd650a94b57bfd7349cbd1a4e57181d3c6fa578bd37669d', u'b1a1a4b1492c0135aa83ac210b29dcaca7f51241f445623ea10d131e7ccedaef', u'db87240673c119a55d082f08a26021f4bb0267f807deec07a496f7901c84f240', u'5b880f71cafda3bbeeb4afe9a072b33f64732662efd34aa73d5e7fb5dd5a9b45']
>>> for h in hashes:
...     h
... 
u'0956cc45b0683797a292844337d7dfe70db0e2f808e3dfebda911055f9027e99'
u'2d758d178fc3b52e749b6a65e5e393dd4883a68ffe1b4cd2839a123168198c40'
u'38a5e47067467749b86fab8708ea3b8e8ca47186d77cb7b0d70dd7ef6ff17934'
u'cb77f6df4309d8c2129a159758b3863ede9077f251f750e2af0144424e709e31'
u'b5c7b93a7166e11a0e20e674bd627f087afd8c0c72b8d840b2bb005740ec24d9'
u'9117bbe7438bf253da3b79241a41799a73ada3c8dd2f5749c397c46c8f1c07cd'
u'fff0ff08d657e1e90fc0f1ee73c68c314b1a56ed921ee735e3677201a63faac5'
u'01ecfcd71bc1224f3a2edd73d4010b43200b68c57028a16a93c90f6c6aa3aa63'
u'63f44a12d7f4159cf76c0c0af17f5e4371cd6a4e14f6f71d4949e3dae25880c4'
u'f010fa8a20b2e828f75d69394d9bbf8a56a69546d53acf66ec652427c293538a'
u'12434b150e8fd180ed0373635c05ba152ea048ae8d635b705c3c5f0148773e8e'
u'58b5a4bb0561423b14a21e0af9d39cd90b40ca809c60465b614192887ac722d0'
u'271ec3f5d556a64e79a9ecf9c1b6bff41e6c55c9d2ea4e3a43f0b5ad4bfb28a3'
u'21c261659e06d2585dff7e747c98bb1d0783008b51ecbf72b6950687f275a898'
u'42f6acd885b786f4bc7ccfd0283499b0e7f5f821777596a22c637eb9c17d457e'
u'718d56cb921ddfda748235b22cea73d31ead9a687aa3ccb112d112385180d648'
u'c54d351e741c7f0a4fd650a94b57bfd7349cbd1a4e57181d3c6fa578bd37669d'
u'b1a1a4b1492c0135aa83ac210b29dcaca7f51241f445623ea10d131e7ccedaef'
u'db87240673c119a55d082f08a26021f4bb0267f807deec07a496f7901c84f240'
u'5b880f71cafda3bbeeb4afe9a072b33f64732662efd34aa73d5e7fb5dd5a9b45'

>>> events = fcr.events.all()
>>> len(events)
42
>>> event_hashes = [e.digital_currency_tx_hash for e in events]
>>> for eh in event_hashes:
...     eh
... 
u'1fd2a01ef5c3d6c172062b173f27a0f38a6275c601bcd82e8b18899f5fe74bfe'
u'46d1a1ed4b2178d5f655076366115a5b763dcfd9c0feaa30fba47c9ff0026e38'
u'fef2c390f8caf5591df0d6393796ff685c7d54f9cf758630b305aaca6266c08c'
u'e4ee59ae8a9b1d851237efb80a66e601921a85cae9c8122a3a7feabe05ff757d'
u'2e968cba162660538db2d9b20a4038932c9223d0f0d878e509efb00b6ee71e0f'
u'aa6da7c80f0dca86a115063e162729524ab6636dd2fc160d1a9866286d02c3cf'
u'd86045f0d57bc378f584accff6a14796d8772ee6d9a73f33954e0bad422eabce'
u'3da6d771f3fe33d831b1c7ffbb8d8f83ef793381898153c9ecfffbb51e3c0f04'
u'1f7e6229dc47552304d387e4179fdd05884757e5cc3e1c07a7552d9892eec965'
u'2db38ef698bfa3e1c49c7dd484795fa1e0578b004233c53c83506b531290f572'
u'4c7c47e0df6a24a6907f1084ddf3ee3543f90a6e45f4c9d9276f3dd15ee5c29b'
u'a11c25fa2e1debab5adf9a039aecef6f763a58f094ed3b9d676d15b5a59d1a07'
u'16224b9224ed8c4d37ca9a03707285902f351100a1328195b28a7fbf3ce8021d'
u'c6feeb4cb288936298213be2b2a5068bd1b900f28f5b6cdd2aec300b426326db'
u'02bd0ec3cfa23920c8976554e5c083cceec40e2bbf925ac24fe60be3b45858fe'
u'aaf69496c83a804ac191a36472a51ad9ae958698a713858e0b428d247946997b'
u'baafee3cadc3fe1f12ea43401ee10623f55309b8ddba207c6012406fa6bd5c11'
u'dd0b1449042a9d895082de70c4a32bb64e3751cc5e9772d4fed65270415d2a7d'
u'623a23ac90dde27b655e60fa0a446a392438a09bf74ce06db1debdf977085f42'
u'b9559cfe2f6d19b57459c6ca1f1c40e4152246da91b4ecf705bd876cce1806ac'
u'a1749e382caf61aa941f7b9beadf4077ee99a90769a7bcb3dfb8b104333c39a9'
u'a23ada076f47e68a9888e913d47d7f7c6852db4f309f708a7cbc29d6bdd38ad5'
u'f0a5aefa961a768ce8b298299b4bdedeb5d0ba0fb9dbf730a510c91a0f5e0033'
u'5b880f71cafda3bbeeb4afe9a072b33f64732662efd34aa73d5e7fb5dd5a9b45'
u'db87240673c119a55d082f08a26021f4bb0267f807deec07a496f7901c84f240'
u'b1a1a4b1492c0135aa83ac210b29dcaca7f51241f445623ea10d131e7ccedaef'
u'c54d351e741c7f0a4fd650a94b57bfd7349cbd1a4e57181d3c6fa578bd37669d'
u'718d56cb921ddfda748235b22cea73d31ead9a687aa3ccb112d112385180d648'
u'42f6acd885b786f4bc7ccfd0283499b0e7f5f821777596a22c637eb9c17d457e'
u'21c261659e06d2585dff7e747c98bb1d0783008b51ecbf72b6950687f275a898'
u'271ec3f5d556a64e79a9ecf9c1b6bff41e6c55c9d2ea4e3a43f0b5ad4bfb28a3'
u'58b5a4bb0561423b14a21e0af9d39cd90b40ca809c60465b614192887ac722d0'
u'12434b150e8fd180ed0373635c05ba152ea048ae8d635b705c3c5f0148773e8e'
u'f010fa8a20b2e828f75d69394d9bbf8a56a69546d53acf66ec652427c293538a'
u'63f44a12d7f4159cf76c0c0af17f5e4371cd6a4e14f6f71d4949e3dae25880c4'
u'fff0ff08d657e1e90fc0f1ee73c68c314b1a56ed921ee735e3677201a63faac5'
u'9117bbe7438bf253da3b79241a41799a73ada3c8dd2f5749c397c46c8f1c07cd'
u'b5c7b93a7166e11a0e20e674bd627f087afd8c0c72b8d840b2bb005740ec24d9'
u'cb77f6df4309d8c2129a159758b3863ede9077f251f750e2af0144424e709e31'
u'38a5e47067467749b86fab8708ea3b8e8ca47186d77cb7b0d70dd7ef6ff17934'
u'2d758d178fc3b52e749b6a65e5e393dd4883a68ffe1b4cd2839a123168198c40'
u'0956cc45b0683797a292844337d7dfe70db0e2f808e3dfebda911055f9027e99'
```

**Comment by bhaugen** [comment] 2017-01-26 17:29
Ok, figured that one out. Should have started to dig into the code in the first place.
```
def address_history_info(address, page = 0, items = 20
```
20 is all it I would get without overriding items...

**Comment by bhaugen** [comment] 2017-01-28 10:43
I deleted a few comments about transactions in the wallet that seemed to be missing, because they were all a result of my mistake in calling address_history_info without expanding the items parameter beyond the default 20.

**Comment by XaviP** [comment] 2017-03-15 23:09
First approach: Now the view knows which tx are in the blockchain, but not in ocp.
https://github.com/FreedomCoop/valuenetwork/commit/f81607290a8462c5849fff13dd71a9002953eaad

Todo: create EconomicEvent (and external Agent??) and incorporate it to the events_list

**Comment by bhaugen** [comment] 2017-03-15 23:29
> Todo: create EconomicEvent (and external Agent??) and incorporate it to the events_list

We should discuss both of those. Should show in the history, but whether to incorporate in OCP depends on the scope of OCP accounting.

**Comment by XaviP** [comment] 2017-03-19 19:52
The code is ready to create Event, but commented the "save" lines: https://github.com/FreedomCoop/valuenetwork/commit/6bcea5b2ee824d7f3222851125128edfc4ced39a#diff-064794c25603502d8d05e73554d2e570R203
I need to make some test in testocp and de-comment.

**Comment by XaviP** [comment] 2017-03-20 07:27
Done: https://github.com/FreedomCoop/valuenetwork/commit/d23faee35f5df3764bb9a485ae7d7ceb0ed99438 
Closing.

**Closed by XaviP** 2017-03-20 07:27 UTC
Labels: help wanted, This sprint

**Comment by bhaugen** [comment] 2017-03-20 10:54
@XaviP congratulations! Where's a good example in testocp?

**Comment by XaviP** [comment] 2017-03-20 11:14
Your personal wallet in testocp could be a good place to test it, if you ever have received faircoins from outside ocp.
